### PR TITLE
Doc: This patch implments markdown format in README.md Fixed & brings it in sync with readme.io contents.

### PR DESCRIPTION
**Pull request by koolhead17**

### CODE REVIEW

**Comment by harshavardhana** [comment]
// cc @GarimaKapoor - are we keeping '1, 2, 3' in front of heading and sub-heading even on github? just wondering.

**Comment by GarimaKapoor** [comment]
Yeah we can keep the numbers to be consistent with the docs.minio.io. Numbers need to be formatted after every number a dot should be added. e.g. 1. 2. likewise

**Comment by koolhead17** [comment]
@GarimaKapoor @harshavardhana made the numbering changes as suggested. 😄

**Comment by harshavardhana** [comment]
LGTM, Thanks :+1:

**Pull request merged**
